@url = http://localhost:8080

@token = eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJtZWRpdHJhY2siLCJzdWIiOiJtY2hhbiIsImFwcF91c2VyX2lkIjoxLCJhdXRob3JpdGllcyI6IlVTRVIiLCJleHAiOjE2ODYxMDg5NTh9.MSS69Xy8xNieM9ez1ouGUqPraNSH67V4jX6itqTg4sk

### 

# POST: Should create token for existing user 
POST {{url}}/authenticate HTTP/1.1
Content-Type: application/json

{
    "username": "mchan",
    "password": "P@ssw0rd!"
}

###

# POST: Should refresh token.
POST {{url}}/refresh_token HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

###

# POST: Should create account
POST {{url}}/create_account HTTP/1.1
Content-Type: application/json

{
    "username" : "test",
    "password" : "P@ssw0rd!",
    "firstName" : "Johnny",
    "middleName" : "",
    "lastName" : "Test",
    "email" : "jt@test.com",
    "phone" : "1-800-test"
}

###

# PUT: Should update account
PUT {{url}}/update_account HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "appUserId": 3,
    "username" : "test",
    "password" : "P@ssw0rd!",
    "firstName" : "Dukey",
    "middleName" : "",
    "lastName" : "Test",
    "email" : "jt@test.com",
    "phone" : "1-800-test"
}

