@url = http://localhost:8080/api

@token = eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJtZWRpdHJhY2siLCJzdWIiOiJtY2hhbiIsImFwcF91c2VyX2lkIjoxLCJhdXRob3JpdGllcyI6IlVTRVIiLCJleHAiOjE2ODYxNTEzMjV9.HKut4CeapRQESoknSYMSp-IgE-1n14dg0Whltc8x6rM

### 

# Exists here to get token
POST http://localhost:8080/authenticate HTTP/1.1
Content-Type: application/json

{
    "username": "mchan",
    "password": "P@ssw0rd!"
}

###

# GET: Should get prescriptions by User Id
GET {{url}}/prescription/user/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

###

# GET: Should get prescription by Id
GET {{url}}/prescription/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

###

# POST: Should add prescription
POST {{url}}/prescription HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "pillCount": "15",
    "hourlyInterval": "4",
    "product_ndc": "00000-7602-4",
    "startTime": "2023-05-31 10:00:00",
    "app_user_id": "1"
}

###

# PUT: Should update prescription
PUT {{url}}/prescription/3 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "pillCount": "5000",
    "hourlyInterval": "235",
    "product_ndc": "00000-0000-0",
    "startTime": "2023-05-31 10:00:00",
    "app_user_id": "1",
    "prescriptionId": 3
}

### 

# DELETE: Should delete prescription
DELETE {{url}}/prescription/3 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
