@url = http://localhost:8080

@token = eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJtZWRpdHJhY2siLCJzdWIiOiJtY2hhbiIsImFwcF91c2VyX2lkIjoxLCJhdXRob3JpdGllcyI6IlVTRVIiLCJleHAiOjE2ODYwODYwMjB9.gQ_DJCuoBQook78v78ElB52IsRKrUEQ_RNxJ7vlZALg

@phoneNumber = 

###

# POST: Should sent textSms
POST {{url}}/api/sms HTTP/1.1
Content-Type: application/json

{
    "phone": "{{phoneNumber}}",
    "message": "REMINDER: Please remember to take X medications at 11:00"
}

###
*modify entity to have boolean for text notifications

1. When medication is added, ask if they want text message notifications

2. If user does not have phone number, prompt for phone Number

3. Display phone number 

4. Display Test sms and ok box